### ISSUE TITLE
add ThreadEvent class to debugSession.ts

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-debugadapter-node#1]
_From @weinand on December 16, 2015 13:1_

@lukehoban I've created this bug for you.

_Copied from original issue: Microsoft/vscode-mock-debug#3_

**Comment by weinand** [comment]
@isidorn fyi

**Comment by felixfbecker** [comment]
Just wanted to file this issue. In the meantime, how can I send a Threads event in my Node-based debug adapter? All the docs say is "VS Code will listen for threads event". How do they look like? Can I use some function of DebugSession to send them manually?

**Comment by weinand** [comment]
@felixfbecker you can always find the details of the debug protocol here: https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts

Please search for  "ThreadEvent".

I've added a concrete class ThreadEvent to the DebugSession, and published a new version of the npm module vscode-debugadapter. Run "npm update" to download this.

**Comment by felixfbecker** [comment]
thanks you :)

**Comment by felixfbecker** [comment]
Would you mind adding it to the export in main.ts? Otherwise I have to manually `import {ThreadEvent} from `vscode-debugadapter/lib/debugSession`

**Comment by weinand** [comment]
Oops, done.
Sorry for this oversight.

BTW, you send events with DebugSession.sendEvent(...).

**Comment by weinand** [comment]
@lukehoban I've added the ThreadEvent to the node module.

**Comment by felixfbecker** [comment]
thanks again
