### ISSUE TITLE
Question about how the callstack is handled for stackframes with unknown source

### ISSUE THREAD

**Issue by StephenBloomquist** [Microsoft/vscode-debugadapter-node#103]
Is there a way to get VSCode to stop sending the "Unable to open 'Unknown Source'" error message when a stackframe with an unknown source is clicked (e.g. just do nothing)? Am I simply not handling or otherwise mishandling something when I get this, or is this an error that comes from behind the scenes?

Thanks!

**Comment by weinand** [comment]
Dup of https://github.com/Microsoft/vscode/issues/20622

**Comment by weinand** [comment]
Should be fixed in Insiders.
