### ISSUE TITLE
[Question] Call vscode API from a debug adapter

### ISSUE THREAD

**Issue by MaxfieldWalker** [Microsoft/vscode-debugadapter-node#107]
I get exception of `Cannot find module 'vscode'` when I call directly vscode API(`vscode.window.showInputBox()`) from a debug adapter to get user input(like stdin).

I think it is possible to call vscode API by sending and hooking custom request or event that asks vscode extension to call the API, but Is that right?

**Comment by weinand** [comment]
@MaxfieldWalker you cannot use the VS Code API in debug adapters because they do not run in an extension host environment.

**Comment by MaxfieldWalker** [comment]
OK, thank you for the explanation.
