### ISSUE TITLE
Debug Protocol: Need a way to control what happens to a process when DisconnectRequest is sent

### ISSUE THREAD

**Issue by andrewcrawley** [Microsoft/vscode-debugadapter-node#111]
There's currently no way to control what happens to a process when a DisconnectRequest is sent.  The current behavior is probably adapter-specific, but in general it seems that if the process was launched by the debugger, it is terminated, and if the process was attached, it is left running.

I propose:

```typescript
export interface DisconnectArguments {
    /** Indicates whether the debugged process should be terminated when the debugger is disconnected. */
    terminateProcess?: boolean;
}
```

If unspecified, the debug adapter would do whatever it thinks is best.  Otherwise, the value of the parameter would determine whether or not the process would be terminated.

Namedrops: @weinand @richardstanton @gregg-miskelly

**Comment by gregg-miskelly** [comment]
Sounds good to me.

**Comment by weinand** [comment]
request makes sense.
