### ISSUE TITLE
Support to kill the log buffering

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-debugadapter-node#112]
The `LoggingDebugSession` starts to buffer all protocol logging until the `setup` method is called (which flushes the buffer).
However, if no logging is needed, there is no way to stop the buffering.

We need a new `LogLevel` value `Stop` that when passed to `setup` stops the buffering (and the logging) so that there is no significant logging overhead.

**Comment by weinand** [comment]
@roblourens I've added the "Stop" enum and added a minimal (but maybe naive) fix to stop all buffering and logging if "logLevel" is set to "Stop".
You might want to revisit this...

**Comment by roblourens** [comment]
On second thought, you might just want to have node-debug set the min loglevel as Error. This change is also fine though. This line keeps any log code from running: https://github.com/Microsoft/vscode-debugadapter-node/blob/2688d532522aab0bbe7f1251d00bbadf5f8645b9/adapter/src/logger.ts#L141 but the early termination is fine.

**Comment by weinand** [comment]
IIRC, without my early termination the messages would still appear on the console: https://github.com/Microsoft/vscode-debugadapter-node/blob/2688d532522aab0bbe7f1251d00bbadf5f8645b9/adapter/src/logger.ts#L150

**Comment by roblourens** [comment]
Only when running as a debug server - https://github.com/Microsoft/vscode-debugadapter-node/blob/2688d532522aab0bbe7f1251d00bbadf5f8645b9/adapter/src/logger.ts#L115

**Comment by roblourens** [comment]
(Which could be annoying too, I'm just used to it)

**Comment by weinand** [comment]
I've closed this since this works for me (but please re-open if you plan to improve something)
