### ISSUE TITLE
debugProtocol.json: `DisconnectArguments` does not define `restart` arg, but VScode sends it

### ISSUE THREAD

**Issue by metaleap** [Microsoft/vscode-debugadapter-node#113]
An oversight? Or is it not supposed to be in the public API/protocol for custom debug servers? Or is `restart` too new, or already deprecated?  =)

**Comment by metaleap** [comment]
I guess I didn't at first completely grasp the "Arguments" concept pervading various areas in the protocol where args are really various non-protocol-prescribed, client-or-server-specific arbitrary things. So closing as I'm assuming "if it isn't in the protocol, it's client-specific"

**Comment by weinand** [comment]
All "arguments" passed to requests should be "protocol-prescribed".
If they are not, then only reason is that they are experimental (and we are not yet sure whether we should promote them to become part of the protocol).

Currently I'm only aware of the "__restart" attribute passed to the "attach" and "launch" request
which I'll add with this issue.

What other non-protocol-prescribed arguments have you found?
