### ISSUE TITLE
Debug protocol: Add "externalCode" option to StackFrameFormat

### ISSUE THREAD

**Issue by andrewcrawley** [Microsoft/vscode-debugadapter-node#117]
The "Just My Code" feature in VS causes stack frames containing non-user code to be collapsed into a single "[External Code]" label.  If users want to see the hidden frames without disabling JMC entirely, they can enable a "Show external code" stack formatting option.  We need to add a member to `StackFrameFormat` to represent this option.

Proposal:

```typescript
export interface StackFrameFormat extends ValueFormat {
    // ...

    /** Displays stack frames containing external code. */
    externalCode?: boolean;

    // ...
}
```

Namedrops: @weinand @gregg-miskelly @richardstanton @pieandcakes

**Comment by weinand** [comment]
Different debug adapters might collapse frames for a different reasons than "External Code", e.g. "Uninteresting Code".
Could we use a name that describes more the purpose in the UI than the reason, e.g. "hideNoFrames" or "allFames" or "expandAllFrames"?

**Comment by gregg-miskelly** [comment]
Sounds reasonable to me.

**Comment by andrewcrawley** [comment]
Yeah, that makes sense.  How about something like:

```typescript
export interface StackFrameFormat extends ValueFormat {
    // ...

    /** Includes all stack frames, including those the debug adapter might otherwise hide. */
    includeAll?: boolean;

    // ...
}
```
