### ISSUE TITLE
The values of presentationHint don't agree between the debug protocol and the debugger implementation

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode-debugadapter-node#118]
I filed a bug on VSCode that the callstack viewer had a typo `presenationHint` instead of `presentationHint`.

https://github.com/Microsoft/vscode/issues/28572#issuecomment-308058986

@isidorn fixed that.  However I also notice that the usage of `StackFrame.presentationHint` and `StackFrame.source.presentationHint` do not correspond to the debug protocol:

https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L1101 

https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L1129

Check out this code in the debugViewer:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L548

Note that it is setting `stackFrame.source.presentationHint` to `label` and `subtle` but the debug protocol says that `Source.PresentationHint` allows only `emphasize` and `deemphasize`.

**Comment by isidorn** [comment]
I think we just need to update our `debugProtocol` that both `stackFrame.source.presentationHint`  and `Source.PresentationHint` have the same potential values.

**Comment by weinand** [comment]
`StackFrame.presentationHint` and `Source.presentationHint`are independent attributes on different types.
- the "presentationHint" on Source is available outside the context of the Stackframe.
- the "presentationHint" on the StackFrame is necessary because not every StackFrame has a source.
