### ISSUE TITLE
stactktrace requests are sent two times in a row.

### ISSUE THREAD

**Issue by kalberes** [Microsoft/vscode-debugadapter-node#119]
Is there any reason why the stacktrace events are sent two times in a raw.
So basically after a stopped event (breakpoint hit) notification I get a thread request than a stacktrace request to which I respond and then again a stacktrace request.
This makes stacktraces appear twice .
Event worst in the experimental build after the stack trace response nothing is shown.
Is there a timeout that a stack trace request has to respond? 
The weird thing that this was working fine (one stacktrace request) until the June update of VsCode.

Thanks
Kalman

**Comment by weinand** [comment]
@kalberes please don't file frontend issues here. The behavior you are seeing is not a protocol issue but an unexpected (but perfectly fine) use of the protocol.

For performance reasons the frontend retrieves the stack in two chunks: the first frame, and the rest. If this doesn't work for you then you are not honouring the "levels" and "startFrame" attributes of the  stacktrace request. You can either fix your implementation of the stacktrace request, or you can wait for the June release where we added an opt-in capability for this feature.

Please see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#debug-adapter-protocol
