### ISSUE TITLE
StackFrame PresentationHint.Subtle is not subtle enough

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode-debugadapter-node#121]
When I set certain stack frames (from "external" code) to "subtle" I get this display:
![image](https://user-images.githubusercontent.com/5177512/27849287-42c51a26-6109-11e7-9eca-32f6a9636dfe.png)
I'm sorry but that is just **too subtle**.  I'm looking at this thinking - there's something different here but I can't quite place it.

This is what I'd like to see for the PowerShell debugger (based on my previous experience using Visual Studio and how it displays external stack frames) - cc @daviwil
![image](https://user-images.githubusercontent.com/5177512/27849472-a1ec9c58-610a-11e7-9e80-481766b65be5.png)
The above is settting the `.stack-frame.subtle` class `color` to `#808080`, ditch the italics.   IMO this makes it much easier for me to identify the stack frames that are in my module (code).  Or is there a way for us to configure the `.stack-frame.subtle` CSS class from our extension.

BTW this is how Visual Studio shows "subtle" in the call stack:
![image](https://user-images.githubusercontent.com/5177512/27849382-15a75bac-610a-11e7-8cf2-1bf15b1e66fb.png)

**Comment by weinand** [comment]
@rkeithhill setting the `presentationHint` on the Source to `deemphasize` should do what you want:

![2017-07-05_09-59-56](https://user-images.githubusercontent.com/1898161/27854967-07c50f8e-6169-11e7-9911-9f5c8fbe17f5.png)

**Comment by rkeithhill** [comment]
That's good to know.  Thanks!

**Comment by rkeithhill** [comment]
Yup, that works.
