### ISSUE TITLE
Debug Protocol: Add a "url" field to "source" objects

### ISSUE THREAD

**Issue by andrewcrawley** [Microsoft/vscode-debugadapter-node#125]
We'd like to add a `url` field to `Source` objects to support more advanced mappings from url to local file that VS can perform based on project system information while debugging JS running in a browser.

Proposal:

```typescript
export interface Source {
    // ...

    /** The URL of the source, if available. */
    url?: string;

    // ...
}
```

We'd prefer a separate field rather than re-using the `path` field so that debug adapters can continue to support their own source mapping mechanisms while still allowing the host to do more advanced mapping if available.

Namedrops: @weinand @richardstanton @gregg-miskelly @digeff @roblourens

**Comment by roblourens** [comment]
Can you tell me more about what additional info you get from the project system? Can this info be encoded in the launch config via `pathMapping` and `sourceMapPathOverrides`, so the adapter can do the mapping?

**Comment by digeff** [comment]
There might be virtual directories, bundles, minified files, symbolic links, and all kind of features that can make the mapping very complex. Some of these features can be language/library/framework specific too.

**Comment by roblourens** [comment]
The adapter typically has to handle those things anyway, and I'd like to make it work in all scenarios.

I've mostly avoided too many framework-specific adjustments, except for some tweaks to handle webpack and meteor-specific sourcemap paths.

**Comment by andrewcrawley** [comment]
Rob informed us that it's already possible to configure the adapter to return urls, so I don't think we need this.  Diego is going to test that out, and I'll re-open the issue if necessary.
