### ISSUE TITLE
DebugProtocol: InitializeRequestArguments should provide the current locale of the client

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode-debugadapter-node#129]
Currently if a debuggerAdapter has localized strings, there is no way (that I see at least) for it to know the locale of the client.

Proposal: InitializeRequestArguments should have a `clientLocale` property that it can use to select the appropriate localized strings. `clientLocale` should be set to one of the language codes in https://electron.atom.io/docs/api/locales/

**Comment by roblourens** [comment]
VS Code starts the debug adapter process with the locale as an environment variable. I think this is more convenient programming-wise so the localization module can be configured immediately when the process starts. It looks like this `"VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}"`. I'm not sure what `availableLanguages` is used for.

It probably makes sense for this to be in the debug protocol too?

**Comment by gregg-miskelly** [comment]
For .NET Debugging, I would definitely like this to be a part of the protocol as opposed to an environment variable as we have scenarios where vsdbg may not be directly spawned by the IDE and therefore it is much nicer to have the information flow through the normal channel instead of having to have a bunch of special code to pass on this one property.

@roblourens would it be much work to make the node adapter support this being provided in the protocol? I ask because for scenarios where VS is hosting the node adapter we should really be supporting loc. So we either need to have VS start setting this environment variable, or we should have the node adapter support whatever protocol extension we pick here.

CC @andrewcrawley

**Comment by weinand** [comment]
@dbaeumer what is the use of `availableLanguages` in the env var `"VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}`?

**Comment by dbaeumer** [comment]
`vscode-nls` is only configured with the locale. So it is sufficient to pass this info to the adapter.

**Comment by weinand** [comment]
@roblourens VS Code now passes the "locale" in the "initialize" request and I'm supporting this in node-debug too with this [code](https://github.com/Microsoft/vscode-node-debug/blob/437e6f8ba289c7df3c41000049ec1c114e321e3e/src/node/nodeDebug.ts#L769-L771).

**Comment by roblourens** [comment]
Did the same for node2
