### ISSUE TITLE
ThreadEvent with reason 'exited' removes all threads

### ISSUE THREAD

**Issue by DatGuyJonathan** [Microsoft/vscode-debugadapter-node#130]
I'm working on a debugger extension that supports multiple stopped threads. When the user clicks 'continue', the debug adapter (DA) handles continueRequest with the backend and responds to VS Code with allThreadsContinued = false. The backend will eventually notify DA that the thread has finished, so DA sends a ThreadEvent with reason 'exited' to VS Code.

If I have multiple stopped threads and perform 'continue' on one of them, VS Code removes all the threads from the call stack view. My workaround is to send a stopped event to VS Code for every thread that the DA knows about, but that seems expensive because the DA will have to handle stackTraceRequest for threads that haven't changed.

Is that workaround the expected behavior from DA?

Here are the versions I'm working with:
VS Code: 1.15.0
vscode-debugadapter & vscode-debugprotocol: 1.22.0

**Comment by weinand** [comment]
I will move this to VS Code, since the issue is about a client implementation problem.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#33839
