### ISSUE TITLE
Support full set of reverse execution commands

### ISSUE THREAD

**Issue by rocallahan** [Microsoft/vscode-debugadapter-node#131]
gdb with rr (http://rr-project.org/) fully supports 'reverse' alternatives to all forward-execution commands. In particular, reverse-step-out and reverse-step-in are supported. However, the VSCode debug protocol doesn't seem to support these. Please add them!

**Comment by weinand** [comment]
@rocallahan what VS Code debugger extension supports gdb with "rr"?

**Comment by rocallahan** [comment]
As far as I know there aren't yet any extensions that explicitly support rr. You can use rr with the Microsoft C++ extension by typing in reverse-execution commands:
https://github.com/mozilla/rr/wiki/Using-rr-in-an-IDE#setting-up-visual-studio-code
I imagine that it would be pretty easy to add proper rr support to this extension: https://marketplace.visualstudio.com/items?itemName=webfreak.debug

**Comment by weinand** [comment]
As soon as some debug extension author asks for it, we'll add it to the protocol.

**Comment by weinand** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!

**Comment by pattontim** [comment]
The new roadmap has the following clause:

> Continue to refine and improve the Debug Adapter Protocol with support from the community.

Meaning this issue should be considered again?
