### ISSUE TITLE
How is the uniqueness of debugger type enforced?

### ISSUE THREAD

**Issue by DatGuyJonathan** [Microsoft/vscode-debugadapter-node#132]
Quick question about the debugger contribution in package.json. The description for type is "Unique identifier for this debug adapter.". It appears that I can install a debugger from marketplace with the same type as the one I'm developing (mine was installed with .vsix). Is that uniqueness enforced anywhere (e.g. during publishing)?

**Comment by weinand** [comment]
No, uniqueness is not enforced by the publishing process.

@isidorn what happens if two debugger extensions contribute the same debug type? Are they merged and the latter wins?

**Comment by isidorn** [comment]
@weinand if there are duplicates they get merged. More details
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L291

**Comment by DatGuyJonathan** [comment]
Okay, thanks for the confirmation.
