### ISSUE TITLE
Breakpoint marker is deleted even though the breakpoint still exists

### ISSUE THREAD

**Issue by DatGuyJonathan** [Microsoft/vscode-debugadapter-node#139]
When the user deletes a breakpoint from the UI, the marker is removed right away then the adapter gets a `setBreakpointsRequest` for that URI without that line breakpoint, so the adapter figures out the breakpoint was deleted. If the adapter fails to delete that breakpoint on the server side, my adapter sends a response that it's still a verified breakpoint. I have an adapter that needs to make a network call to create/delete a breakpoint, so it's possible a delete fails. In this scenario, the client UI says the breakpoint is deleted, but the server still has it enabled.

What's the suggested way to stop VS Code from deleting that breakpoint?

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#39198
