### ISSUE TITLE
Debugger fails when I hover over a variable (and at times even before hitting the first breakpoint)

### ISSUE THREAD

**Issue by harikb** [Microsoft/vscode-debugadapter-node#14]
Environment: MacOSX 10.10.5 (Yosemite, not El Capitan). Latest VS Code 0.10.11
Debugging Golang via Delv. However the error message does not seem to be from delv.
Go plugin is the current most popular plugin `lukehoban.Go`
![image](https://cloud.githubusercontent.com/assets/952886/13791203/2990332e-eaa9-11e5-934f-176470e75af8.png)

I am able to use Delve directly for debugging.

**Comment by weinand** [comment]
@harikb the delv debug adapter seems to send some unexpected data back via stdout or stderr. This breaks the communication mechanism between VS Code and the debug adapter.

Moving to Go extension.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-go#260
