### ISSUE TITLE
Debug type case sensitive

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-debugadapter-node#15]
While implementing a debug adapter, we need to declare what debug type it is like 

```
"contributes": {
		"debuggers": [
			{
				"type": "Ruby",
				"label": "Ruby Debugger",
                                ...
```

It works perfectly when user set type as `Ruby` in their launch config while it breaks when users type `ruby` with the lowercase `r`. It somewhat confuses users of my tiny plugin. 

Meanwhile if I attempt to change the type value from `Ruby` to `ruby`, my extension will never be backwards-compatible. Is there any solid reason that we make it Case-Sensitive or is there any workaround? You know that we are likely to name our debugger as the language name, `Python` for any python related code, `PowerShell` for ps code, but users might get blocked if they type `python` or `Powershell`.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#4563
