### ISSUE TITLE
TerminateThreadRequest

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-debugadapter-node#150]
A client should be able to request to terminate a thread. Should include a capability to indicate whether it's supported by the runtime/adapter.

In vscode, this would probably just be a context menu option on the thread item of the callstack. An extension could implement this easily by contributing a context menu command and sending a custom debug request. Although the context menu command would show up on every row of the callstack, not just threads: https://github.com/Microsoft/vscode/issues/19180

```ts
/** TerminateThread request; value of command field is 'terminateThread'.
	The request starts the debuggee to run again.
*/
export interface TerminateThreadRequest extends Request {
	// command: 'terminateThread';
	arguments: TerminateThreadArguments;
}

/** Arguments for 'terminateThread' request. */
export interface TerminateThreadArguments {
	threadId: number;
}
```

cc
@mostafaeweda
@ebluestein

**Comment by weinand** [comment]
See https://github.com/Microsoft/vscode-debugadapter-node/commit/9457a850257dbc6c93ef9c55a155c231f859db50
