### ISSUE TITLE
Add Apex to the VS Code Debugger Protocol Implementation Page Wiki

### ISSUE THREAD

**Issue by ntotten** [Microsoft/vscode-debugadapter-node#158]
Looks like wiki editing is disabled so I'm opening an issue. :)

We have implemented the VS Code Debugger Protocol for the Salesforce Apex Language. We would like it added to [the wiki](https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations)

**Name**: Apex
**Github Usernames**: 
**Organization**: Salesforce
**Repository**: https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-apex-debugger

**Comment by weinand** [comment]
Thanks!
