### ISSUE TITLE
Client path on Windows is not decoded

### ISSUE THREAD

**Issue by DatGuyJonathan** [Microsoft/vscode-debugadapter-node#159]
I have a customer on Windows 7 whose debugging session could not hit a breakpoint because of an error like this:
`Unable to open '[file name]': File not found (file:///c:/Users/username/foo/Apex%20Debugger%20sample/blah/blah.cls)`

The customer was able to start a session, set breakpoints, etc. My debugger extension is initialized with `setDebuggerPathFormat('uri')`. When a `stacktraceRequest` comes in, I create StackFrames with Sources whose paths use `convertDebuggerPathToClient()`. Is there anything else a debugger extension should do to prepare the path for VS Code on Windows?

**Comment by weinand** [comment]
Probably you are the first debugging using `convertDebuggerPathToClient` for the 'url' path format.

**Comment by DatGuyJonathan** [comment]
@weinand , here are the before and after for a path with a space in it:

![image](https://user-images.githubusercontent.com/7286437/36817543-598a690c-1c96-11e8-85eb-632d9feae374.png)

I've had success with paths on Windows if I use:
> import Uri from 'vscode-uri';
> Uri.parse(sourceUri).fsPath

**Comment by weinand** [comment]
I'm using now our own "vscode-uri" module for bot directions.

**Comment by DatGuyJonathan** [comment]
@weinand , to clarify, will there be an update to `vscode-debugadapter-node/adapter/src/debugSession.ts` to use `vscode-uri`? I see this issue got added to March 2018 milestone, but it got closed.

**Comment by weinand** [comment]
I've published the prerelease version (1.28.0@next) of the node modules.

**Comment by DatGuyJonathan** [comment]
@weinand , thanks for publishing that. uri-to-path looks good, but I think it broke path-to-uri.

<img width="1440" alt="screen shot 2018-03-07 at 9 56 10 am" src="https://user-images.githubusercontent.com/7286437/37109510-0b073982-21ef-11e8-8d87-b0a502b85243.png">

See screenshot that shows the Windows drive name is `c%3A` instead of `c:`. I think it's the same issue as `https://github.com/Microsoft/vscode-languageserver-node/issues/105`. Would you be able to replace the `%3A` to `:` if it's Windows?

**Comment by weinand** [comment]
I've published another prerelease version (1.28.0@next) with a fix.
