### ISSUE TITLE
LaunchRequestArguments should include noDebug attribute

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-debugadapter-node#16]
[debugProtocol.ts:197](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L197)
As this is shared for all debug adapters and comes from VS Code, debug adapters should not need to add this to their interface if they extend the protocol interface

**Comment by weinand** [comment]
@felixfbecker this will probably break you because an empty interface LaunchRequestArguments behaves quite differently than an interface with one member...
I had to remove the LaunchRequestArguments type from DebugClient.launch(...).
If you have a better solution please let me know.

**Comment by felixfbecker** [comment]
@weinand I tried 1.8.0-pre.1 and I have no issues at all in both cases where
 - I already had added `noDebug` to my own interface (no problem since it is the same type)
 - I did not add anything (no problem since it is an optional property)

It should not break anything.
