### ISSUE TITLE
add a capability event

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-debugadapter-node#160]
Sometimes it is difficult for a DA to know and return all capabilities from the Initialise request because some might not be known until the runtime/debugger has been started.

This request asks for a new "capabilities" event that can be used at a later time.

Since the capabilities are dependent on the frontend and its UI, it might not be possible to change that at random times (or too late). Consequently the "capabilities" event has a "hint" characteristic: a frontend can only be expected to make a "best effort" in honouring individual capabilities but there are no guarantees.
 
/cc @gregg-miskelly @andrewcrawley @richardstanton @rodrigovaras @isidorn @roblourens

**Comment by weinand** [comment]
Proposal:
```ts
/** Event message for 'capabilities' event type.
    The event indicates that one or more capabilities have changed.
    Since the capabilities are dependent on the frontend and its UI, it might not be possible to change that at random times (or too late).
    Consequently this event has a hint characteristic: a frontend can only be expected to make a 'best effort' in honouring individual capabilities but there are no guarantees.
*/
export interface CapabilitiesEvent extends Event {
	// event: 'capabilities';
	body: {
		/** The set of updated capabilities. */
		capabilities: Capabilities;
	};
}
```

**Comment by gregg-miskelly** [comment]
LGTM

**Comment by andrewcrawley** [comment]
I assume the expected behavior is that adapters should send the full set of capabilities in this event, and not just the changes - is this correct?

**Comment by weinand** [comment]
Since all capabilities are optional, the expected behavior is to only send those capabilities that have changed. This is similar to the capabilities returned from the Initialize request: the DA is only expected to return those capabilities where it wants to differ from the default.

The "full" set of capabilities is dynamic anyway because new capabilities are added frequently and DAs based on an older schema do not not know the current full set.

**Comment by andrewcrawley** [comment]
Sorry, by "full set of capabilities" I mean the full set supported by the adapter, not every possible capability.  That is, the set of capabilities sent in this event should replace the set of capabilities sent in the `initialize` response.

**Comment by gregg-miskelly** [comment]
I think if a debugAdapter specifies a capability in the `initialize` response, and then sends a `capabilities` event that doesn't mention that capability, the state of that capability should still be what was sent in the `initialize` response. In other words, I don't think we need a way to say 'please return this capability to an unspecified default state'.

**Comment by weinand** [comment]
Currently VA Code merges additional capability sets into the initial set received in the `initialize`response. And I think this is the intuitive behavior expected from all frontends.

This means that a capability event can either return the "full set of capabilities supported by the adapter" or just the changed attributes. The result will be the same.
However, from a code size and performance perspective sending the changed attributes is preferable.

I will reword the sentence "The event indicates that one or more capabilities have changed." to make clear that only changed capabilities need to be returned and that all other values remain their values.
