### ISSUE TITLE
Last message sent by debug adapter to VS Code during termination

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode-debugadapter-node#164]
Here's an excerpt from the docs. 
> . In both cases and in the case that the target terminated normally or crashed the debug adapter must fire a terminated event. After receiving a response from the disconnect request, VS Code will terminate the debug adapter.

* Assume the debugged program runs to completion
* Debug adapter sends the terminated event to VSCode. 

**Question 1:** Will vscode now send a disconnect request to the debug adapter (after vscode received the terminated event)

Based on the docs it sounds like terminated is not the last message in the debug session life cycle.

**Question 2:** Is there such a thing as the last message sent to VS Code. 
Is the the `terminated` event the last message or is it the response to `disconnect` the last message sent to VS Code (assuming `terminated` is sent before the response to `disconnect` request).

**Comment by weinand** [comment]
@DonJayamanne Are you still interested in answers? You closed this yourself...

**Comment by DonJayamanne** [comment]
That's fine, I checked the source in vscode. However i wouldn't mind some feed back from you. Thanks
