### ISSUE TITLE
Which capabilities support delayed changes?

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode-debugadapter-node#165]
I need to do a remote debugger, so the capabilities should be told me by the debugger at the remote.But I can only know where the remote debugger is after `LaunchRequest` or `AttachRequest`. However, `LaunchRequest` or `AttachRequest` can only be received after `InitializeResponse` is returned.

I tried `CapabilitiesEvent`, but `supportSetSetVariable` and `supportsConditionalBreakpoints` could not be changed. I just sent `CapabilitiesEvent` after `InitializeResponse`.

Is there any other way to deal with this problem?

**Comment by weinand** [comment]
You can send capabilities "later" as a Capabilities event. This was introduced in the February release. Please see https://code.visualstudio.com/updates/v1_21#_debug-adapter-protocol

What  capabilities do you want to send later?

**Comment by actboy168** [comment]
I tested `supportSetSetVariable` and `supportsConditionalBreakpoints` and both failed.

**Comment by actboy168** [comment]
The order I send is `InitializeResponse`,`CapabilitiesEvent`,`InitializedEvent`. And they should be send at the same time.

**Comment by weinand** [comment]
You can send the `CapabilitiesEvent` at any time, but currently the VS Code implementation only honours the "supportsStepBack" capability. Please file an issue for the unsupported capabilities   at https://github.com/Microsoft/vscode/issues.
