### ISSUE TITLE
How to correctly response StackTraceRequest?

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode-debugadapter-node#169]
My debugger sometimes has a bug. There are two identical stack frames in the vscode UI.

I found that vscode will send StackTraceRequest three times and my response is as follows

```
Step 1.

StackTraceRequest:
startFrame = 0
levels = 1

StackTraceResponse:
stackFrames
* frame id = 2
totalFrames = 1

Step 2.

StackTraceRequest:
startFrame = 0
levels = 20

StackTraceResponse:
stackFrames
* frame id = 2
* frame id = 3
* frame id = 4
totalFrames = 3

Step 3.

StackTraceRequest:
startFrame = 1
levels = 19

StackTraceResponse:
stackFrames
* frame id = 2
* frame id = 3
* frame id = 4
totalFrames = 3
```

Then the UI will display 4 stack frames
* frame id = 2
* frame id = 2
* frame id = 3
* frame id = 4

![1](https://user-images.githubusercontent.com/1836844/37552465-2c9d232c-29f1-11e8-8192-06d30749480f.png)

My frame id starts at 2 and I don't know what effect.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#46099
