### ISSUE TITLE
If a request method returns a promise that gets rejected, send error response

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-debugadapter-node#17]
Currently in dispatchRequest you catch synchronous exceptions and automatically send an error response. As I converted all my methods to async functions (and used promises before anyway) this doesn't work in 99% of the cases, as the methods return a promise. I have to wrap every single method in a try/catch block with sendErrorResponse. It would be nice if dispatchRequest could check if the return value is a promise, and if yes, attach a catch listener to it that also sends an error response. (I would just override dispatchRequest to do it on my own, but the return value is swallowed).

**Comment by weinand** [comment]
his feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!
