### ISSUE TITLE
VariablePresentationHint values do not change UI

### ISSUE THREAD

**Issue by osstekz** [Microsoft/vscode-debugadapter-node#173]
Seems no matter the values set in a variable's "presentationHint", no changes are visible in the UI.  Could not find another project implementation to compare against like MockDebug or Mono.  Is VariablePresentationHint fully implemented? Specifically "readOnly" does not disable/block user from executing a setVariable.

`0425 DBUG dbg_adapter.vala:268: queue_outp_message [Content-Length: 1257RNRN{"seq":36,"type":"response","success":true,"message":null,"request_seq":10,"command":"variables","body":{"variables":[{"name":"Time","value":"23:52:05","type":"date","presentationHint":{"kind":"data","attributes":["rawString"],"visibility":"public"},"evaluateName":null,"variablesReference":0},{"name":"gSD","value":"struct StructData","type":"struct","presentationHint":{"kind":"data","attributes":["rawString","readOnly"],"visibility":"public"},"evaluateName":null,"variablesReference":0},{"name":"gint2","value":"299","type":"int","presentationHint":{"kind":"data","attributes":["rawString"],"visibility":"public"},"evaluateName":null,"variablesReference":0},{"name":"gstr1","value":"GLOB STR","type":"string","presentationHint":{"kind":"data","attributes":["rawString"],"visibility":"public"},"evaluateName":null,"variablesReference":0},{"name":"oHelloClass","value":"HelloClass *","type":"ptr","presentationHint":{"kind":"data","attributes":["rawString","readOnly"],"visibility":"public"},"evaluateName":null,"variablesReference":0},{"name":"helloclass_properties[2]","value":"static GParamSpec *","type":"ptr","presentationHint":{"kind":"data","attributes":["rawString","readOnly"],"visibility":"public"},"evaluateName":null,"variablesReference":0}]}}]`

**Comment by weinand** [comment]
An attribute with the term "hint" in its name is just a "hint". There is no guarantee that a particular frontend honours a hint. 

Many hints are honoured by VisualStudio but not by VisualStudio Code.
If you find "hints" not honored by VS Code, please file feature requests against VS Code (and not against the protocol).
