### ISSUE TITLE
Debugging Server Protocol planned?

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode-debugadapter-node#175]
It's great that this has been split into a separate repo. I was wondering if Microsoft has a DSP (Debugging Server Protocol) on their roadmap?

It would be the logical next step and I'd assume also a great long term step for Visual Studio Code and not only.

Are there any plans for an explicit Debugging Server Protocol?

**Comment by mickaelistria** [comment]
While the repo here contains both spec ( https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json ) and implementation for vscode, I believe the content of the spec can already be perceived as an explicit "Debug Adapter Protocol".
If you look at the wiki, you'll see that the documentation is similar to what LSP provided some monthes ago, and you'll find out multiple implementations. Some other IDEs/editors like Eclipse IDE, Eclipse Che and soon (Eclipse) Theia do have support for this debug adapter protocol and are able to connect to debuggers that support the protocol.
So to me, the current state is somehow what you're asking for. So do I understand it right that what you propose if mostly to have a separate Git repo for the spec?

**Comment by costincaraivan** [comment]
I'd guess I was thinking mostly about branding. The Language Server Protocol was promoted quite a bit by Microsoft, that's very important for adoption. This spec... I had to dig through Github issues and random internet sites to find it.

It's a shame for all the hard work involved to not go the extra 20%.

So I guess I was thinking about a separate Git repo, preferably a Github Pages site, or a page on a Microsoft site about it, a blog post on the VS Code site? Something to use to engage the Internet's hype machine 😄

**Comment by egamma** [comment]
>Some other IDEs/editors like Eclipse IDE, Eclipse Che 

@mickaelistria actually Visual Studio is now supporting it as well.

**Comment by egamma** [comment]
@costincaraivan also please notice it is called the `Debug Adapter Protocol` and intentionally not the `Debug Server Protocol`.

**Comment by costincaraivan** [comment]
@egamma Yeah, sorry, I was going by analogy with the Language Server Protocol. But in the end the Debug Adapter Protocol would serve an analog role: smoothing out differences between various debugging tools to allow interoperability with a range of IDEs (vs smoothing out differences between various custom protocols for IntelliSense to allow interoperability with a range of IDEs). Or am I misunderstanding?

**Comment by egamma** [comment]
@costincaraivan yes, pls see https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations.

**Comment by weinand** [comment]
See https://code.visualstudio.com/blogs/2018/08/07/debug-adapter-protocol-website

**Comment by LinArcX** [comment]
Hello guys. How can I implement a dap for vim? Is there any effort to bring this awesome capability to vim world?
