### ISSUE TITLE
Auto completion debug protocol issues 

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode-debugadapter-node#176]
https://github.com/Microsoft/vscode-java-debug/issues/294

We have implemented completion request for java debugger, however there two issues for this protocol: 
1. Trigger completion request. Only be triggered at the start when input in the debug console window, if we put "." for the object, it will not be triggered another time. 

> 2. For method, if the insert text with additional (), the () will be omitted.

**Comment by weinand** [comment]
I don't know what you are proposing.
Is there a concrete problem with the debug adapter protocol or is there a problem with the VS Code implementation of the protocol?

**Comment by yaohaizh** [comment]
For the first, on the language server side, there is an CompletionContext to specify the trigger character, but it cannot be specify on the debug protocol. Not sure if this is an UI issue. 

> 
> CompletionContext
> 
> Contains additional information about the context in which completion provider is triggered.
> Properties
> 
> triggerCharacter?: string
> 
> triggerKind: CompletionTriggerKind

Second should be our own problem, just ignore it.

**Comment by weinand** [comment]
A debug adapter can specify the trigger characters with the `completionTriggerCharacters` [Capability](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Capabilities).
