### ISSUE TITLE
Variable modification/access breakpoints

### ISSUE THREAD

**Issue by tsmaeder** [microsoft/vscode-debugadapter-node#181]
I haven't found support for breaking on modification or access to a variable. Java, for example would support such breakpoints.

**Comment by roblourens** [comment]
Sorry, I had the wrong issue reference in my commit.

**Comment by weinand** [comment]
DAP has no support for this at the moment but I'm interested to add something like this.

@tsmaeder could you please provide some more information, e.g.
- potential UI/UX
- proposed DAP protocol requests

**Comment by weinand** [comment]
DAP supports [DataBreakpoints](https://microsoft.github.io/debug-adapter-protocol/specification#Types_DataBreakpoint) for quite some time now. Closing.
