### ISSUE TITLE
Logger intercepts SIGINT and SIGTERM improperly

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-debugadapter-node#198]
- Start debugging node2 DA in server mode
- Start a node app against it
- Stop the DA
- Have to press stop a second time

**Comment by weinand** [comment]
I do not want to change the library that late in the release cycle and suggest that we fix this for September.
Is this acceptable for you?

**Comment by roblourens** [comment]
That's fine 👍 

I think we are a bit late for 2017 anyway...
