### ISSUE TITLE
List debugprotocol in the 'typings' registry?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-debugadapter-node#20]
Since vscode-debugprotocol is really a .d.ts, it might make sense to list it in 'typings' (used to be tsd). Just a suggestion. https://github.com/typings/typings

**Comment by felixfbecker** [comment]
I am a maintainer of https://github.com/typings/registry. I think this would fit very well under the `common` registry. If you need help, please hit me up.

**Comment by weinand** [comment]
With the advent of @types support in npm we don't need this.
