### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-debugadapter-node#22]
Now that VS Code 1.0 is out I would like to publish my release that I have ready for almost a month now. It currently depends on the 1.8 pre-versions (`noDebug` attribute, `defaultTimeout` attribute, ...) though, and I would like to publish with a dependency on the stable versions. Any ETA for 1.8?

**Comment by egamma** [comment]
@isidorn do you have additional insights?

**Comment by weinand** [comment]
@felixfbecker the stable version for the npm modules that correspond to VS Code 1.0 is 1.7.0.
`noDebug` etc. will be part of the April release. I will bump the version of the npm modules to 1.8.0 (stable) at the end of April.

**Comment by felixfbecker** [comment]
@weinand But VS Code 1.0 includes the "Run without Debug" action, so the protocol should document/provide this option. And I don't understand why the testsupport update needs to wait for the next VS Code release, if it's just about features like `defaultTimeout` for tests

**Comment by weinand** [comment]
@felixfbecker support for everything you need is available in the pre-release version of 1.8. So please use that version.

**Comment by felixfbecker** [comment]
@weinand So you recommend to use pre-versions for stable releases of adapters too?

**Comment by weinand** [comment]
@felixfbecker for the time being, yes. We will get into a better rhythm after the 1.0 swirl.

**Comment by weinand** [comment]
I've bumped the version number for the three modules to 1.8.0
