### ISSUE TITLE
[question] Enable wire logging in vscode

### ISSUE THREAD

**Issue by yyoncho** [microsoft/vscode-debugadapter-node#220]
How can I enable and view the logging between vscode and the debug adapter?

Sorry if this is not the correct place to ask the question.

**Comment by roblourens** [comment]
There isn't any built in logging but if you are writing a debug adapter you can use https://github.com/microsoft/vscode-debugadapter-node/blob/master/adapter/src/loggingDebugSession.ts

It is used by the chrome and node debug adapters.
