### ISSUE TITLE
Upgrade node to the latest version used in VSC stable

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-debugadapter-node#226]
Hi Python extension VS Code dev here 👋

VS Code is shipping with Node 12.4.0, due to which we have to now run the tests under that same version instead of 10.*. Some of our tests are dependent on this package, and as it still uses the old node version, tests fail. (https://github.com/microsoft/vscode-python/issues/9383)

 Please upgrade the node version you're shipping with.

**Comment by roblourens** [comment]
Sorry, I'm not sure exactly what you are asking for. This is just a library that will run in whatever version you run it in.

**Comment by karrtikr** [comment]
I see, sorry I didn't know about this.
Actually we had this [line](https://github.com/Microsoft/vscode-python/blob/2b6a8f2d439fe9d5e66665ea46d8b690ac9b2c39/src/test/debugger/portAndHost.test.ts#L67-L71) in the test,
```typescript
await Promise.all([
    debugClient.configurationSequence(),
    debugClient.launch(<launchArgs>),
    debugClient.waitForEvent('initialized')
]);
```
which fails with `Error: spawn ENOMEM` at `<vscode-python>\node_modules\vscode-debugadapter-testsupport\src\protocolClient.ts:76:20` on upgrading node version to 12.
 It uses the package APIs, so I figured it might be happening because the package is still using the old node version.

Can you see someway in which upgrading node might lead to failure for these sequence of API calls?

**Comment by roblourens** [comment]
`spawn ENOMEM` I dunno, is your system almost out of memory?

**Comment by karrtikr** [comment]
That's what the error says. But I was wondering what made the package (`\src\protocolClient.ts:76:20`) throw that error, I think it's coming when call to `debugClient.launch(<launchArgs>)` is made.

**Comment by roblourens** [comment]
I don't think so. This library just passes the commands along to your debug adapter and is pretty simple. So I would look at your debug adapter's code more closely. Like figure out exactly what is going wrong first, is your debug adapter crashing or is it the runtime that your DA spawns, etc.

**Comment by karrtikr** [comment]
I see. As we're not sure of what the cause is exactly, we can probably close this.
