### ISSUE TITLE
Breakpoints not supported while debugging an application running in a container

### ISSUE THREAD

**Issue by jeffmaury** [microsoft/vscode-debugadapter-node#227]
I tried to debug a node based application running in a container through the attach mode and noticed that the breapoints are not supported (they are ignored).
Is this a limitation of the Debug Adapter Protocol ? Or an issue in the Node adapter ?

**Comment by puremourning** [comment]
It’s not a limitation of the protocol.

**Comment by mickaelistria** [comment]
Does the node debug adapter have some options to map local client-side vs remote/deployment URLs?

**Comment by mickaelistria** [comment]
This can be closed as the vscode-nodedebugadapter has `localRoot` and `remoteRoot` parameters to handle this case.

**Comment by weinand** [comment]
Correct, either use the "localRoot" and "remoteRoot" attribute of the debug configuration for debug type "node" or just use the [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension.
