### ISSUE TITLE
Can you release a new version? 

### ISSUE THREAD

**Issue by fxsg20151212** [microsoft/vscode-debugadapter-node#231]
Hello, the latest version is 1.29.0, but it is a long time ago. Will a new version be released recently?

**Comment by weinand** [comment]
The latest released version is 1.41.0.

**Comment by fxsg20151212** [comment]
But the release page is still 1.29.0 version, can you  release 1.41.0 in this page?

![image](https://user-images.githubusercontent.com/16264691/86553050-3be5fe80-bf7c-11ea-8771-0f5126afb3a5.png)

**Comment by weinand** [comment]
why? you get the latest release via npm.
