### ISSUE TITLE
Would you consider exporting `ProtocolClient`?

### ISSUE THREAD

**Issue by eliben** [microsoft/vscode-debugadapter-node#232]
We have a need to write DAP middleware and are looking for a DAP *client*. The `ProtocolClient` class in `testSupport/src/protocolClient.ts` fits the bill but it's not exported. `DebugClient` is exported but it seems very much tied to a testing lifecycle.

Would you consider exporting `ProtocolClient`, or is it only meant for testing scenarios and we should develop our own client for other purposes?

**Comment by roblourens** [comment]
It's only meant for testing, but you might fork that code as a starting point for whatever you want to do.
