### ISSUE TITLE
Being able to prevent editing a type hint

### ISSUE THREAD

**Issue by ncannasse** [microsoft/vscode-debugadapter-node#255]
First, sorry if I'm posting into the wrong place for such question.

The Hashlink VM debugger displays some object type information in place of both the "value" and "type" of the variable, as the following screenshot shots :

![image](https://user-images.githubusercontent.com/1022912/144712511-82233a03-cc27-423f-8f81-304659f1e49a.png)

This is nice to be able to know the exact instance type of your objects especially when dealing with subclasses.
However atm, the value itself can be edited. Is there a way to mark it as "read only" to prevent the double click to enter edit mode ? Or alternatively, a way to not set any value and instead be able display the type ?

Best Regards,
Nicolas

**Comment by connor4312** [comment]
Yes, in the [VariablePresentationHint](https://microsoft.github.io/debug-adapter-protocol/specification#Types_VariablePresentationHint) you can assign `readOnly` as an attribute. Let us know if that doesn't work or you have further questions.

**Comment by ncannasse** [comment]
Thanks @connor4312 for the answer. However setting  `presentationHint : { attributes : ["readOnly"] }` on the variables does not seem to have any effect. I'm currently using VSCode 1.55.2, was it implemented on more recent VSCode version?

**Comment by connor4312** [comment]
Yea, this is something I fixed in I think 1.62.
