### ISSUE TITLE
Debug protocol extension: editing variables

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode-debugadapter-node#27]
To be able to use the debug protocol in other IDEs (Visual Studio, Xamarin Studio) or VS Code in the future we should think about how the debug protocol should support editing variables. Something like:

    export interface SetValueRequest extends Request {
        variablesReference: number;
        newValue: string;
    }

Note that I would expect this to be able to fail with a message (ex: the new value has a syntax error), but I think a normal error response could be used there.

Seems like we might also want some sort of 'isEditable' attribute on evaluate results to let the IDE know if editing should be allowed.

**Comment by daviwil** [comment]
I know @rkeithhill would definitely be interested in this for the PowerShell extension.

**Comment by weinand** [comment]
I've added a first cut of a 'SetVariableRequest' to the debug protocol:
https://github.com/Microsoft/vscode-debugadapter-node/commit/333b1234d07fbf9a2f742487bdc54d87f4f0b570 and https://github.com/Microsoft/vscode-debugadapter-node/commit/38a49b2a3cb0f90ff6d2c0f19249483f898f6809

**Comment by gregg-miskelly** [comment]
Looks good to me. One suggestion: in the [description for the request](https://github.com/Microsoft/vscode-debugadapter-node/commit/333b1234d07fbf9a2f742487bdc54d87f4f0b570#diff-e8f377e7d1e8d2e389f06b43df73b0b6R475) do you think we should try and call out that support for the command is optional?

**Comment by weinand** [comment]
@gregg-miskelly sure, I will add more details to the description after I've used this in node-debug. I just wanted to get this into VS Code so that we can build the UI and explore the details.

**Comment by gregg-miskelly** [comment]
Cool. I didn't realize you guys were planning to support it in the UI. Sounds great.

**Comment by weinand** [comment]
@gregg-miskelly our current development model is to only add things to the debug protocol that we've used ourselves. Only exception so far is the module view. So we are excited to get a PR for that. :-)

**Comment by gregg-miskelly** [comment]
Got it. How do you want to handle then features which aren't in VS Code? For example, I imagine it will be a while before you get it https://github.com/Microsoft/vscode-debugadapter-node/issues/34, but you might want it some day, where as we will need it soon for Xamarin studio. Do we just want to agree on something in these issues?

**Comment by weinand** [comment]
@gregg-miskelly with #34 we are closer than you think... yes, we will agree on something (but in both directions).

**Comment by gregg-miskelly** [comment]
@weinand that is great to hear! However, it still seems like at least one of the [issues I opened](https://github.com/Microsoft/vscode-debugadapter-node/issues/created_by/gregg-miskelly) is something that it will be a while before it makes sense to add to VS Code, right? If so, how would you like to handle this? We would like make sure that we add to the protocol in a way that your team is happy with.

**Comment by weinand** [comment]
@gregg-miskelly right, if we are happy with a feature request, then we have no problems adding it to the protocol. Currently we are going through your [issues](https://github.com/Microsoft/vscode-debugadapter-node/issues/created_by/gregg-miskelly) and we will raise all concerns and discuss them with all stakeholders one by one.
Seeing implementations, adoptions, and PRs on all fronts is an excellent way to validate (protocol) designs and to foster progress.

**Comment by rkeithhill** [comment]
PowerShell has some variables that are constant/readonly.  I assume we can set the `response.success` to `false` and if we provide a `response.message`, VSCode UI would display that, right?

**Comment by weinand** [comment]
@rkeithhill yes, exactly that would be the way to deal with read only variables.

**Comment by gregg-miskelly** [comment]
@weinand in our discussions on the 'type' thread, I realized that there is one other item we would probably want here -- 

    interface Variable
    {
        ...
        // Optional string that is the initial value if the user attempt to edit this variable. If not
        // provided, 'value' is used instead. This is used for the case that the debug adapter
        // and/or underlying debugger have done steps to improve the display of the variable
        // which makes the value invalid syntax (ex: include the type of the value in 'value')
        editableValue?: string;

**Comment by weinand** [comment]
@gregg-miskelly @daviwil @rkeithhill @jacdavis @felixfbecker @lukehoban @roblourens @DonJayamanne @WebFreak001 @rebornix
A first version of 'variable editing' support is now available in the Insider build (node-debug) and the 'next' version of the debug protocol.
Still missing is the UI for showing errors.

**Comment by weinand** [comment]
We've added the UI for showing errors returned from the `setVariablesRequest`

**Comment by wesrupert** [comment]
I second @gregg-miskelly's suggestion to add an editableValue string to Variable. Currently since Variable only contains `name` and `value` as display properties, the only way to show type information is to format it into `value`, e.g. `i: 3 [int]`. This means that when the user clicks into the field to edit it, they have to clear out the `[int]` part of the string every time. Being able to pass separate edit and display values would make this experience a lot cleaner.

**Comment by weinand** [comment]
@wesrupert please consider to make use of the `type` attribute which will become available in the June release. See https://github.com/Microsoft/vscode-debugadapter-node/issues/32

**Comment by wesrupert** [comment]
@weinand Great! I'll work on updating the plugin based on the new protocol changes.

**Comment by gregg-miskelly** [comment]
@weinand support for `type` will definitely reduce our need for this, but editableValue is a concept we have in VS for other scenarios too - sometimes its useful to have a display name which is different than the editable value. Consider a character pointer in C++ for example. The editable value might just be something like 0x123456 where the display could be '0x123456 "The string value pointed to goes here"'. I couldn't tell you off hand all the scenarios where we have an editable value which is different from the display value, but I do know that we have them even for C#.

**Comment by weinand** [comment]
@gregg-miskelly I see the need, but not for this sprint. Please adopt what will be available in June and we can iterate over the issues after that.

**Comment by gregg-miskelly** [comment]
@weinand will do. Would you like us to open an issue for adding this for the future?

**Comment by rkeithhill** [comment]
@weinand I have a question about the [protocol](https://github.com/Microsoft/vscode-debugadapter-node/blob/333b1234d07fbf9a2f742487bdc54d87f4f0b570/protocol/src/debugProtocol.ts#L484).  The setVariableRequest type defines `name` to be of type `number`.  But when I look at in the debugger, it is coming across as a string.  String makes sense to me but how can this work if the .ts is typed as a `number`.  The magic of JavaScript?  ConfusedInColorado.  :-)

**Comment by weinand** [comment]
@rkeithhill your 'protocol' link from above refers to an erroneous commit.
This problem no longer exists in the 1.11.0 version of the protocol:
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts

**Comment by rkeithhill** [comment]
My sanity has been restored.  Thanks!
