### ISSUE TITLE
Debug protocol extension: support obtaining the full value for a string variable

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode-debugadapter-node#33]
To be able to use the debug protocol in other IDEs (Visual Studio, Xamarin Studio) or possibly VS Code in the future we should think about how the debug protocol should support large strings. Currently the debug adapter can clip strings, but if the UI has a facility for showing the full string (in VS this is done through a 'string visualizer' see image) the debug protocol doesn't support a way of obtaining this 'raw' string.

![stringvisualizer](https://cloud.githubusercontent.com/assets/11078489/16026962/25b7b266-3187-11e6-95a7-8c05f750c99b.JPG)

Suggestion: 
- Add new 'rawString' request which takes a variableReference as input and returns the string.
- Add a flag to the Variable interface to indicate that the rawString is available.

**Comment by weinand** [comment]
@gregg-miskelly VS Code uses already an 'evaluate' request to retrieve the raw value of a string (e.g. for the 'Copy value' action).

**Comment by gregg-miskelly** [comment]
@weinand we need some way to differentiate a normal expression evaluation from a request to get the full string value. It doesn't matter for small strings, but if we have a several megabyte string, one doesn't necessarily want to fetch that by default.

**Comment by weinand** [comment]
@gregg-miskelly a `variableReference` only exists for structured variables but not for simple (=leaf) variables. So an API would require both a `variableReference` of the parent and the name of the variable within its parent.

**Comment by weinand** [comment]
Starting with debug protocol v1.14.0 we've introduced a new attribute `evaluateName` on the `Variable` type. This can be used to access the raw value via an `evaluate` request.
