### ISSUE TITLE
Debug Protocol: breakpoint hit counts

### ISSUE THREAD

**Issue by jacdavis** [Microsoft/vscode-debugadapter-node#37]
In order to use the vscode protocol in vs and xamerin, we would need the ability to support breakpoint hit counts. This is similar to a breakpoint condition, but allows the debug engine to control the number of times a bp would be hit. We currently support four types of hit counts:
public enum enum_BP_PASSCOUNT_STYLE { 
   BP_PASSCOUNT_NONE             = 0x0000,
   BP_PASSCOUNT_EQUAL            = 0x0001,
   BP_PASSCOUNT_EQUAL_OR_GREATER = 0x0002,
   BP_PASSCOUNT_MOD              = 0x0003
};

These are:
1) No hit count (default)
2) hit count equal to a value
3) hit count greater than or equal to a value
4) hit count is a multiple of a hit count.

The VS interface for this provides the user's value (number of interest) and a type:
https://msdn.microsoft.com/en-us/library/bb146656.aspx

**Comment by weinand** [comment]
I propose to add a string typed "hitCount" attribute to the breakpoints requests.
The frontend would provide UI for editing this attribute and the backend would have to interpret the string appropriately. E.g. the 3 VS options from above could be encoded as '= n', '>= n', and '% n'.
node-debug would only accept a positive integer.

**Comment by roblourens** [comment]
I think it would be easier to work with if the 'type' was broken out into an enum or string, like in the VS protocol.

**Comment by weinand** [comment]
@roblourens how should we support this in the UI then?

**Comment by roblourens** [comment]
Actually, I agree - I was imagining that every debug adapter would implement the same 4 types. But if it's up to the debug adapter to implement it their way with their options, we should just provide an input box, pass the input along, and let the debug adapter interpret it.

**Comment by DavidKarlas** [comment]
In XS, this will work fine, we will just hardcore our enum values to logical expressions.(not really sure why first two options are useful :))
![image](https://cloud.githubusercontent.com/assets/774791/18632013/78f193d0-7e75-11e6-8016-e40281db2b38.png)

**Comment by jacdavis** [comment]
I believe this proposal will work for VS as well.
