### ISSUE TITLE
Debug Protocol: Data Breakpoints

### ISSUE THREAD

**Issue by jacdavis** [Microsoft/vscode-debugadapter-node#38]
In order to the vscode protocol in VS, we would need support for data breakpoints in the protocol. These are currently a native only feature, but one of the most commonly requested features in managed (requiring clr changes). 

The minimum fields would be
1) threadid the databp applies to (optional)
2) a data expression to be evaluated to an address
3) The size of number of elements (limited by hardware, but other runtimes may not have this limitation. 

The VS ui only supports data breakpoints when a value changes, but we do get asked for read data breakpoints sometimes.

**Comment by weinand** [comment]
his feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!

**Comment by gigimushroom** [comment]
why not add data breakpoint

**Comment by coderoid** [comment]
+1 on this issue, this will be hugely useful,

**Comment by igrr** [comment]
Data breakpoints support would be quite useful for C code debugging. Please consider this for the next year's roadmap.

Including "watchpoint type" field (with possible values: read, write, access) would be great.
