### ISSUE TITLE
Debug Protocol: Support step-into-specifc

### ISSUE THREAD

**Issue by jacdavis** [Microsoft/vscode-debugadapter-node#39]
In order to use the vscode protocol in vs and xamerin, we'd need to support Step-into-specific. This is a feature that allows the user to select which call a step in should occur on when there are multiple calls on a line. Users primarily use this when there are a lot of calls on a single line (either implicit or otherwise).

This is a trivial example:
![stepintospecific](https://cloud.githubusercontent.com/assets/13489917/16324034/de15d060-3964-11e6-8602-db98629c67ab.png)

The apis around this would require the debug adapter to provide a list of calls at a specific line. The user would then select one. The target call would then be placed as an optional field in the step-in request.

**Comment by weinand** [comment]
@jacdavis sounds similar to https://github.com/Microsoft/vscode-debugadapter-node/issues/28, correct?

**Comment by gregg-miskelly** [comment]
@weinand not really. Set next statement alters the instruction pointer in an artificial way. Step-into-specific is a special kind of step request which does a combination of step-over and step-into to only step-into one specific call site.

**Comment by weinand** [comment]
@gregg-miskelly @jacdavis @DavidKarlas

I've created a proposal for this protocol addition as this [PR](https://github.com/Microsoft/vscode-debugadapter-node/pull/44).

Please review and comment.
