### ISSUE TITLE
add an "origin" attribute to the debug protocol's "Source" type

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-debugadapter-node#5]
VSCode shows the description "internal module" in the editor's title for contents that doesn't come from a file but is returned from a debug adapter. For content that is inlined into a source map the description "internal module" is misleading.

I propose that we add an attribute "origin" to the debug protocol's "Source" type.

@isidorn what do you think? Is "origin" a good name or do you have a better suggestion?

**Comment by isidorn** [comment]
I like this, we would fix the hack that I just give it the internal module name if it has a reference > 0.
:+1: "origin" sounds good and precise to me
