### ISSUE TITLE
Create a (json) schema for the VS Code Debug Protocol

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-debugadapter-node#51]
Instead of keeping the specification of the VS Code Debug Protocol as a [TypeScript d.ts file](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts) we should introduce a language neutral json schema for it.

An example for this is the Chrome Debugger Protocol schema:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/v8_inspector/js_protocol.json (they are not using a json schema but their own invention).

Ideally we could generate client and server libraries for different implementation languages for this.
So the [debugProtocol.d.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts) could be the result of this.

For a similar discussion about the Language Protocol see: https://github.com/Microsoft/language-server-protocol/issues/25

**Comment by roblourens** [comment]
Relevant projects - https://github.com/nojvek/chrome-remote-debug-protocol translates Chrome's protocol.json to a .d.ts
https://github.com/nojvek/noice-json-rpc - Proxy-based json rpc helper

**Comment by DavidKarlas** [comment]
Hi Andre,

I'm wondering when do you plan to publish .json file?

Regards,
David

**Comment by weinand** [comment]
@DavidKarlas this week is our endgame week for the August release.
I couldn’t yet find the time to finish the schema and publish it in the repository.

I’ll try my best to make something available by the end of this week.

**Comment by DavidKarlas** [comment]
Ok, Thank you for info.

**Comment by weinand** [comment]
@DavidKarlas the first half of the schema and a generator for TypeScript is now available in this repository.

**Comment by weinand** [comment]
The [json schema](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json) for the VS Code Debug Protocol is complete and from now on considered the 'truth'. The TypeScript definitions are generated from it.
