### ISSUE TITLE
Setting Variable in UI that fails will attempt to set bad value again if user clicks elsewhere

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode-debugadapter-node#55]
I'm in the middle of implementing this cool feature for the PowerShell extension.  I could be doing something wrong but what I notice is if I try to set a value to a variable that is readonly, I get the error message in the UI as expected.  But when I try to click somewhere else to dismiss the error UI, VSCode sends the setVariableRequest again, so we wind up in a bit of a vicious loop.

I can understand why you'd want to apply the value when use clicks away but perhaps you shouldn't do that if A) the last attempt was an error and B) the current value has not changed from the value used during the previous failed attempt. 

However, in the case of a readonly/constant variable, no amount of futzing with the value will. I see that pressing `Esc` helps in this case but things get out of sync a bit until I step again in the debugger:

![vscode-debug-issue1](https://cloud.githubusercontent.com/assets/5177512/17839970/84ca99fc-67b6-11e6-8c80-5dcf62b214b0.gif)

You can see the extensions says no - you can't set an int to `42a` and you get an error message to that effect. So I press `Esc` and things look good.  The value goes back to 42 until I close and re-open the `Autos` container.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#10881
