### ISSUE TITLE
support conditional breakpoints

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-debugadapter-node#6]
extend the debug protocol to support conditional breakpoints (and other additional breakpoint attributes).

**Comment by weinand** [comment]
fyi @isidorn

**Comment by isidorn** [comment]
@weinand looks good but why call it `expression` and not `condition`

**Comment by weinand** [comment]
@isidorn good question. Probably because the corresponding argument to the "evaluate" request is called "expression" too. But you are right, we should change this to condition.

**Comment by weinand** [comment]
@isidorn I've pushed the name change

**Comment by isidorn** [comment]
Thanks will adopt it right now
