### ISSUE TITLE
'origin' in SourceResponse vs Source

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-debugadapter-node#61]
It might make sense for the 'origin' property to be returned as part of the SourceResponse vs the Source object on a StackFrame, since the only place it's currently surfaced is when vscode requests the source from the debug adapter. Also, since the Source is used other places where the origin won't be applicable.

But if we want to show the origin in the callstack before a source request happens, it should stay on the Source.

**Comment by weinand** [comment]
@roblourens yes, we should have the option to show the source's origin in the callstack before a source request happens. So let's keep `origin` on Source.
