### ISSUE TITLE
Support for 'type' in SetVariableResponse

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode-debugadapter-node#66]
Now I can't change the variable's type in SetVariable.
![11](https://cloud.githubusercontent.com/assets/1836844/18962500/afecbd52-86a3-11e6-8d66-dc7572a18aef.gif)

**Comment by weinand** [comment]
@actboy168 please elaborate what exactly you are asking for.

**Comment by actboy168** [comment]
My extension will be change the variable's type in SetVariable request,e.g. from string to integer.But,vscode GUI has not changed.

**Comment by weinand** [comment]
You mean the type that is shown when hovering over the value does not change?

**Comment by actboy168** [comment]
Yes.

**Comment by weinand** [comment]
Since this is a bug in the UI I will move this issue over to VS Code and create a new protocol extension request for the missing "type" attribute.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#13881

**Comment by roblourens** [comment]
Also relevant: https://github.com/Microsoft/vscode/issues/12019

**Comment by weinand** [comment]
@roblourens thanks for pointing that out!
