### ISSUE TITLE
Promise API instead of callbacks

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-debugadapter-node#68]
VS Code is now on Node 6 which means we can use async/await. Please return a promise for `runInTerminalRequest`.

The callback doesn't even follow Node's error-first style, so how are errors handled? Promises would allow this as well.

Imo it would also be nice to make the whole DebugSession more oriented around promises. 
You currently catch synchronous exceptions, but if one of the request handlers returns a rejected promise (if it is an async function that means it "throws" an error) it is not catched. I have try/catch around every method handler. Instead of `sendResponse`, why not simply use the value the promise resolves to as a response? This could all be implemented in a backwards-compatible manner.

**Comment by weinand** [comment]
dup of #17

**Comment by felixfbecker** [comment]
This was specifically for the callback in `runInTerminalRequest`
