### ISSUE TITLE
Support a variablesReference in OutputEvent

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode-debugadapter-node#79]
In javascript it is possible to send arbitrary objects to the console (e.g. `console.log(document.body)`). It would be useful if such an object could be inspected in the vscode debug console. Note that this is already possible for evaluation results (via `EvaluateResponse.body.variablesReference`).

**Comment by weinand** [comment]
@hbenl how would this work for node.js? VS Code does not control the implementation of `console.log(<object>)`. Node's implementation pretty prints the object to stdout (which is captured by the debug adapter as a string and then sent as an OutPutEvent).

@roblourens how would this work in chrome-debug or node-debug2?

**Comment by roblourens** [comment]
In chrome-debug, there's an event from the protocol that I listen to for log messages. I could use that in node-debug2, but I just use stdout/stderr at the moment, just because of those messages that are printed to stderr at startup, that aren't captured in the debug protocol.

**Comment by weinand** [comment]
And this event represents exactly what? Every call to `log()`? And the event contains the unmodified object passed to log?

**Comment by roblourens** [comment]
There's `Runtime.consoleAPICalled`, and `Runtime.exceptionThrown`. The first gives the type of console API that was called and its list of arguments, which are in the same format that you get variables or eval results in. So if an object was logged, I can query for its properties on demand.

The second gives an `ExceptionDetails` object with stacktrace, exception object, etc.

**Comment by hbenl** [comment]
So it sounds like this would also work for node.js. And `Runtime.exceptionThrown` sounds like another use case for this feature: uncaught exceptions could be sent to the VS Code debug log and the user could then inspect them there.

**Comment by weinand** [comment]
More information:
- CDP API: [`Runtime.consoleAPICalled`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#event-consoleAPICalled)
- `Runtime.consoleAPICalled` is not supported in v8 debugger protocol, so node-debug won't be able to support this (without monkey patching console.log).

Proposal:

**Comment by roblourens** [comment]
Hm, I think I would be ok with an array, although in cases like where the it's just logging a bunch of strings, I would probably `.join(' ')` the in the adapter.

On the other hand, it might still be useful beyond `console.log`, it looks like `print` in PHP and Python at least accept multiple things to print.

**Comment by isidorn** [comment]
@weinand multiple trees in one row are not currently on the horizon.
Also passing it via an array goes well with our general moto of always fetching variables lazily.

Due to the above I vote for option 2.

Also note that the vscode frontent can workaround option 1 and create a parent element because multiiple tree in one row are not supported. But this feels ugly to me.
Also if we introduce multiple trees in a row in the future we could still display them nicely using option 2. Point is both options still leave flexibility to the UI to display data as needed.

**Comment by roblourens** [comment]
If we were going to have UI for it in the future, it seems like option 1 would be better so we can tell the difference between `console.log(obj1, obj2)` and `console.log([obj1, obj2])` at some point. I can imagine someone complaining about it. But if it's going to be an ugly hack now or a lot of work, I don't think it's worth it, and option 2 would be fine.

**Comment by weinand** [comment]
@roblourens in option 2 we can distinguish between `log(obj1, obj2)` and `log([obj1, obj2])` as well: in the former case the VariableRequest returns 2 variables of type object and in the latter case 1 variable of type array. This could be expressed by wrapping the arguments with another array: `log([obj1, obj2])` and `log([[obj1, obj2]])`. The UI would then remove the outer array.

**Comment by weinand** [comment]
I've added an optional attribute `variableReference` to the OutputEvent.
@roblourens please consider to use this in the CDP based debug adapters.
