### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-debugadapter-node#8]
`<nitpicking>`

You recently added conditional breakpoints, which is a new, backwards compatible feature, and therefor should see a minor version bump, not a patch. Deprecating API in a patch release is very weird.

 > Given a version number MAJOR.MINOR.PATCH, increment the:
 > 
 > MAJOR version when you make incompatible API changes,
 > MINOR version when you add functionality in a backwards-compatible manner, and
 > PATCH version when you make backwards-compatible bug fixes.

`</nitpicking>`

**Comment by weinand** [comment]
thanks.
