### ISSUE TITLE
Formatting Hints for requests that return displayable values

### ISSUE THREAD

**Issue by richardstanton** [Microsoft/vscode-debugadapter-node#84]
Several protocol requests ask for displayable information, such as the name of a stack frame or the value of a variable. There is the possibility that the IDE would like to have the information displayed using an alternative format. For example it is very useful to see the value of a variable in hexadecimal. This proposal is to add a Format property to these requests. The format property will contain an object that may have additional properties specifying formatting hints.

Some formats are added to the protocol in this proposal that could be used by multiple IDEs. However as an object additional properties could be added.
 
```
/** Arguments for 'stackTrace' request. */
export interface StackTraceArguments {
  // ...
  /** Specifies details on how to format the stack frames. */
  format?: StackFrameFormat;
}
/** Arguments for 'variables' request. */
export interface VariablesArguments {
  // ...
  /** Specifies details on how to format the values. */
  format?: ValueFormat;
}
/** Arguments for 'evaluate' request. */
export interface EvaluateArguments {
  // …
  /** Specifies details on how to format the result. */
  format?: ValueFormat;
}
 
/** Provides formatting information for a value. */
export interface ValueFormat {
  /** Displays the value in hex. */
  hex?: boolean;
}
 
/** Provides formatting information for a stack frame. */
export interface StackFrameFormat extends ValueFormat {
  /** Displays parameters for the stack frame. */
  parameters?: boolean;
  /** Displays the types of parameters for the stack frame. */
  parameterTypes?: boolean;
  /** Displays the names of parameters for the stack frame. */
  parameterNames?: boolean;
  /** Displays the values of parameters for the stack frame. */
  parameterValues?: boolean;
  /** Displays the line number of the stack frame. */
  line?: boolean;
  /** Displays the module of the stack frame. */
  module?: boolean;
}
```

Proposed pull request: #82 

@weinand
@jacdavis @gregg-miskelly @andrewcrawley @tzwlai

**Comment by weinand** [comment]
Question about Stacktrace format: the `StackTraceRequest` returns stack frames as structured objects, that is module and line number information are returned as separate attributes.
If the `format` attribute of a StackTraceRequest specifies to **not** display the line number and the module name what does this mean for the debug adapter? The adapter returns these as separate StackFrame attributes and does not "format" them into the StackFrame `name` attribute. Should the adapter just drop the line and module information from the StackFrame object?

**Comment by richardstanton** [comment]
@weinand I think the format attributes should only affect the stack 'name' returned by the debug adapter. My reasoning for this is that the format should only affect how information is displayed, but info on the stack frame like the module and line are also used for code navigation and functional aspects of debugging.

**Comment by weinand** [comment]
@richardstanton you are suggesting these formatting hints on every request that returns a formatted value. Would the values for these hints really vary from request to request?

If we would introduce a new `ConfigureFormattingRequest`that allows to set these values at any time,  
would that be sufficient?

**Comment by richardstanton** [comment]
@weinand I found that formatting changed more frequently than expected. Hitting a breakpoint for example usually has a few calls to the stackTraceRequest each with different purposes. Some requesting formatting, while others are just to get the source information for navigation. I preferred combining the formatting with the request so that formatting state wouldn’t need to be tracked. However, I believe it would also be possible to implement this with a separate request. What would the ConfigureFormattingRequest look like? How would it specify formatting for different requests?

**Comment by roblourens** [comment]
I'm looking into this for node2 in VS, and I don't totally understand the purpose of the StackTraceFormat. ValueFormat makes sense, because there might be a case where only the debug adapter can format a value accurately. But since the stack trace contains all the information needed, why can't the frontend format it the way it wants to?

**Comment by gregg-miskelly** [comment]
@roblourens two reasons:

1. Only two of those format specifies could be done by a frontend (line and module). So this way all of the formats can be handled in a uniform way.
2. In VS at least, there isn't a conical stack frame format. So how the node debugger decides to stick line and file name in the frame is different from how the C#/C++ debuggers do it.

![node](https://cloud.githubusercontent.com/assets/11078489/26127386/00900838-3a3e-11e7-8ef0-cf787fe6f606.PNG)
![cpp](https://cloud.githubusercontent.com/assets/11078489/26127388/024e053a-3a3e-11e7-9169-4b2ff631a08e.PNG)

**Comment by andrewcrawley** [comment]
@roblourens Plus, the formatting options let us respect the user's preferences in VS:

![image](https://cloud.githubusercontent.com/assets/17841637/26127715/f675b072-3a3e-11e7-9a84-fb3d8d02c750.png)

**Comment by roblourens** [comment]
Ok. It still feels weird to have the debug adapter format a string instead of returning structured data, but I see why it makes sense for the debug adapter to drive this.
