### ISSUE TITLE
Add Dart Code to VS-Code-Debug-Protocol-Implementations page

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-debugadapter-node#86]
I noticed at https://github.com/Microsoft/vscode/issues/13353#issuecomment-253170446 that there's a list of implemented debug adapters that you may be notifying of important changes:

https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations

Since it's a Wiki page, it seems I can't send a PR to add ours to it, so here's the info if you'd like to add:

**Name:** [Dart Code](https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code)
**GitHub ID:** @DanTup @devoncarew
**Repository:** [Dart-Code/Dart-Code](https://github.com/Dart-Code/Dart-Code)

**Comment by weinand** [comment]
@DanTup thanks for the info, I've added it to the table.
