### ISSUE TITLE
Support setScriptSource

### ISSUE THREAD

**Issue by jkrems** [Microsoft/vscode-debugadapter-node#91]
One of the major productivity wins of using Devtools is the ability to edit the code while the app is running. It's a bit tricky in node because of the potential node-style CommonJS wrapper but it should be possible to sync editor changes to the running node process.

**Comment by weinand** [comment]
The [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) provides this functionality already based on file watching.
This proves that DAP support is not needed to implement this feature.

**Comment by roblourens** [comment]
Er, it could, but it doesn't yet.

**Comment by roblourens** [comment]
I know we talked about it awhile ago and I don't remember whether @auchenberg prototyped it.

**Comment by auchenberg** [comment]
I didn't as we got Webpack HMR working, which moved the responsibility
outside of VS Code and enables a cleaner architecture.

**Comment by weinand** [comment]
his feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!

**Comment by jkrems** [comment]
Would you accept an external contribution that adds an `{Update,Edit,Set,Whatever}SourceRequest` to the protocol?
