### ISSUE TITLE
Support links to source locations in OutputEvents

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode-debugadapter-node#94]
When you write to the browser console in Firefox or Chrome (e.g. `console.log("foo")`), the console will show a clickable link to the source location of the `console.log(...)` call. Please support links to source locations (i.e. a `Source` object with line and column) in the debug protocol and VS Code.
![screenshot_2017-01-14_13-57-01](https://cloud.githubusercontent.com/assets/16060807/21954984/689f953e-da61-11e6-979e-114bf7f6a9e1.png)

**Comment by weinand** [comment]
@roblourens would it work for the Chrome/Inspector debuggers if we just add a "Source" attribute to the Output event?

**Comment by roblourens** [comment]
Yes

**Comment by hbenl** [comment]
I found that it is already possible to output links to source locations: if the message in an OutputEvent contains `<filepath>:<line>:<column>`, then that part of the message is turned into a link.
But it would still be nice to have explicit support for these links and have them rendered as in the attached screenshot:
- the (absolute) `filepath` is usually quite long, the link should only show the filename (and perhaps the full path in a tooltip)
- the link should be rendered separate from the message

**Comment by weinand** [comment]
I've added `source`, `line`, and `column` attributes to the `Output` event.
