### ISSUE TITLE
Protocol support for SetClientUI

### ISSUE THREAD

**Issue by WardenGnaw** [Microsoft/vscode-debugadapter-node#96]
VsDbg-UI and VsDbg need to know what client to set. 

Debug adapters sometimes provide instructors back to users. Such as edit launch.json or open the launch options dialog. 

A suggestion would be to put it in InitializeRequestArguments' Properties.

```
"client-ui": {
   "type": "string",
   "enum": [ "VSCode", "Unknown" ]
}
```

**Comment by WardenGnaw** [comment]
@wesrupert @andrewcrawley

**Comment by DavidKarlas** [comment]
I think this should be solved via "supportsXXX" in InitializeRequestArguments like https://github.com/Microsoft/vscode-debugadapter-node/blob/978950c457998e1db78f58b6870c3dd041bc77dd/debugProtocol.json#L480-L491
In example given: "supportsEditLaunchJson" and "supportsOpenTheLaunchOptionsDialog"... So VS, VSfM(XS) and other IDEs can also implement this commands if they want...

Special casing IDEs in adaptors is not good idea imo...

**Comment by gregg-miskelly** [comment]
Capabilities are definitely the preferred model, and it is a good solution most of the time. But there are some cases where it doesn't really make sense. For example, the C# debugger has error messages that tell users what option to tweak to enable a certain feature, and the instructions for this are always going to differ from one IDE. Solving this via `capabilityHasVisualStudioDebugOptionsPage` feels too fine grain to me.

@WardenGnaw I don't think 'Unknown' really makes sense as a value. I might also suggest adding at least VisualStudio as a valid value since support for that is under active development.

**Comment by WardenGnaw** [comment]
So if we are keeping it in the initialize request, and addingin Visual Studio and removing special casing. It would look like

```
"client-ui": {
   "type": "string",
   "enum": [ "visualstudio", "vscode" ]
}
```

**Comment by chuckries** [comment]
Is this something we actually need to introduce into the protocol? I believe could solve this for VsDbg-UI and VsDbg by making the clientUI an optional command line arg and making it part of the invocation of the executable rather than sending this via the protocol.

**Comment by gregg-miskelly** [comment]
Definitely could work. But for our remote scenarios I think a protocol message would be easier.

**Comment by weinand** [comment]
Having a string typed `clientID` on the `InitializeRequestArguments` makes sense, but I'd prefer to keep the protocol neutral and not to use an enum with predefined clients here.
An enum will always segregate clients into well known clients (part of the protocol) and unknown clients (not part of the protocol). I suggest that we instead maintain a list of client IDs on a wiki page in the debug protocol repo similar to the [debug adapter list](https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations).

I propose:
```json
"clientID": {
    "type": "string",
    "description": "The ID of the (frontend) client using this adapter. For a list of client IDs see ..."
}
```

**Comment by gregg-miskelly** [comment]
Sounds good to me.

**Comment by wesrupert** [comment]
I think the string ID solution is best as well. :+1:

**Comment by weinand** [comment]
I've created this [Wiki page](https://github.com/Microsoft/vscode-debugadapter-node/wiki/Client-IDs) for maintaining the list of client IDs.
Please let me know what IDs I should add or change.

**Comment by mickaelistria** [comment]
Can you please add "Eclipse IDE (LSP4E connector)" into the list, with clientId=lsp4e.debug ?

**Comment by egamma** [comment]
@weinand and do not forget to add VS.

**Comment by weinand** [comment]
@mickaelistria I've added Eclipse to the list
@egamma VS was always there

![2018-04-20_17-09-53](https://user-images.githubusercontent.com/1898161/39058993-a91909de-44bd-11e8-9452-a63efffbec1e.png)

**Comment by mickaelistria** [comment]
Thanks @weinand !
