### ISSUE TITLE
${Env.<envvar>} not getting expanded in PowerShell debug configuration

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode-debugadapter-node#99]
This [page](http://code.visualstudio.com/docs/editor/debugging) says:

> You can also reference environment variables through ${env.Name} syntax (e.g. ${env.PATH}). Be sure to match the environment variable name's casing, for example ${env.Path} on Windows.

Yet I'm finding with our PowerShell extension, no value gets passed to the PowerShell debugger for the specified environment variable.  Is there something we need to do in the extension e.g. call an env var expansion API to make this work?

**Comment by weinand** [comment]
@rkeithhill variable expansion happens on the VS Code side. No debug adapter is involved in this.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode#20022
